version: '3'

services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/mpp-hw
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G 